/* This file is generated by Ziggy. */
declare module "ziggy-js" {
  interface RouteList {
    "sanctum.csrf-cookie": [];
    "ignition.healthCheck": [];
    "ignition.executeSolution": [];
    "ignition.updateConfig": [];
    telescope: [
      {
        name: "view";
        required: false;
      },
    ];
    home: [];
    "articles.index": [];
    "articles.show": [
      {
        name: "article";
        required: true;
        binding: "id";
      },
    ];
    "admin.login": [];
    "admin.": [];
    "admin.dashboard": [];
    "admin.me.edit": [];
    "admin.me.update": [];
    "admin.logout": [];
    "admin.articles.index": [];
    "admin.articles.create": [];
    "admin.articles.store": [];
    "admin.articles.show": [
      {
        name: "article";
        required: true;
      },
    ];
    "admin.articles.edit": [
      {
        name: "article";
        required: true;
        binding: "id";
      },
    ];
    "admin.articles.update": [
      {
        name: "article";
        required: true;
        binding: "id";
      },
    ];
    "admin.articles.destroy": [
      {
        name: "article";
        required: true;
        binding: "id";
      },
    ];
    "admin.articles.publish": [
      {
        name: "article";
        required: true;
        binding: "id";
      },
    ];
    "admin.articles.unpublish": [
      {
        name: "article";
        required: true;
        binding: "id";
      },
    ];
    "admin.access_logs.index": [];
    "admin.tags.index": [];
    "admin.tags.store": [];
    "admin.tags.show": [
      {
        name: "tag";
        required: true;
      },
    ];
    "admin.tags.update": [
      {
        name: "tag";
        required: true;
        binding: "id";
      },
    ];
    "admin.tags.destroy": [
      {
        name: "tag";
        required: true;
        binding: "id";
      },
    ];
    "admin.images.store": [];
  }
}
export {};
